export {Tools as PageTools}  from "./Tools"
export {Articles as PageArticle}  from "./Articles"
export {About as PageAbout} from "./About"
export {Layout as PageLayout} from "./Layout"
export { Adm as PageAdm } from "./Adm"
export{Cadastrar as PageCadastro} from "./Cadastrar"
export{Login as PageLogin} from "./Login"